---

- name: Install documented dependencies.
  package:
    name:
      - curl
      - unzip
    state: present
  when: not uninstall
  tags:
    - install
    - dependencies

- name: Install documented Debian dependencies.
  apt:
    name:
      - apt-transport-https
      - python-apt
      - python3-apt
      - gnupg
    state: present
  when:
    - not uninstall
    - ansible_os_family == "Debian"
  tags:
    - install
    - dependencies

- name: Setup packages.microsoft.com repository.
  include_tasks: repository.yml

- name: Unzip the onboarding package from Microsoft Defender Security Center.
  include_tasks: onboarding_setup.yml

- name: Manage the mdatp package from Microsoft.
  include_tasks: package.yml

- name: Check for install log.
  stat:
    path: "{{ install_log }}"
  register: mdatp_install_log
  when: ansible_verbosity > 2
  tags:
    - debug

- block:
  - name: Load install log contents.
    command: "cat {{ install_log }}" # noqa no-changed-when
    register: mdatp_install
    tags:
      - debug

  - name: "DEBUG: Print mdatp install log to console."
    debug:
      msg: "{{ mdatp_install.stdout }}"
      verbosity: 3
    tags:
      - debug

  when:
    - mdatp_install_log.stat.exists is defined
    - mdatp_install_log.stat.exists
    - mdatp_install_log.stat.size > 0
