---

- name: Install documented dependencies.
  package:
    name:
      - curl
      - unzip
    state: present
  tags:
    - install
    - dependencies

- name: Install documented Debian dependencies.
  apt:
    name:
      - python-apt
      - gnupg
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - install
    - dependencies

- block:
  - name: Setup mdtap repository from microsoft.com.
    include_tasks: add_repo.yml

  - name: Unzip the onboarding package from Microsoft Defender Security Center.
    include_tasks: onboarding_setup.yml

  - name: Install the mdatp package from Microsoft.
    include_tasks: install_mdatp.yml

  when: not uninstall

- name: Remove the mdatp package.
  include_tasks: uninstall_mdatp.yml
  when: uninstall
  tags:
    - uninstall

- name: Check for install log.
  stat:
    path: /var/log/microsoft/mdatp_install.log
  register: mdatp_install_log
  tags:
    - debug

- block:
  - name: Load install log contents.
    command: "cat /var/log/microsoft/mdatp_install.log" # noqa 301
    register: mdatp_install
    tags:
      - debug

  - name: "DEBUG: Print mdatp install log to console."
    debug:
      msg: "{{ mdatp_install.stdout }}"
      verbosity: 2
    tags:
      - debug

  when:
    - mdatp_install_log is defined
    - mdatp_install_log.exists
    - mdatp_install_log.size > 0
