---

- name: Create MDATP directories.
  file:
    path: /etc/opt/microsoft/mdatp/
    state: directory
    mode: 0755
    owner: root
    group: root
  tags:
    - onboarding

- name: Extract onboarding package.
  unarchive:
    src: "{{ onboarding_source }}"
    dest: /etc/opt/microsoft/mdatp
    creates: /etc/opt/microsoft/mdatp/mdatp_onboard.json
    mode: 0600
    owner: root
    group: root
    remote_src: "{{ '://' in onboarding_source | ternary('yes', 'no') }}"
  register: unarchive_out
  ignore_errors: yes
  tags:
    - onboarding

- name: "DEBUG: output from onboarding unzip attempt."
  debug:
    var: unarchive_out

- name: Custom error handling for configuration unzip.
  fail:
    msg: "mdatp configuration json did not unzip successfully."
  when:
    - unarchive_out is defined
    - unarchive_out.failed
    - not 'Failed to find handler' in unarchive_out.msg
